name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html allure-pytest
        playwright install

    - name: Start local server
      run: |
        python -m http.server 3000 &
        sleep 10
      working-directory: web

    - name: Run Playwright tests with HTML and Allure reports
      run: |
        mkdir -p allure-results html-report
        pytest \
          tests/m3_locators/test_locators_recommended.py \
          tests/m4_basic_actions/test_check.py \
          tests/m5_advanced_actions/test_dialogs.py \
          --html=html-report/index.html \
          --self-contained-html \
          --alluredir=allure-results
      env:
        HEADLESS: true
        SLOW_MO: 0

    - name: Deploy HTML report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: html-report
        publish_branch: gh-pages